### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by nicohagen** [Falx/StoredAnimaCounter#4]
The addon is checked active in the addons list in game, i got the latest version. Still, running `/sac config` tells me "Enter /help for  a list of commands" / comman unknown. It also does not show up in the ElvUI data texts config. Other addons loaded are ElvUI, BenikUI and WeakAuras. I am om english game locales. Any proposals appreciated 👍 .

**Comment by Falx** [comment]
It would seem I depend on some Ace libraries being present, that were not shipped with StoreAnimaCounter. I will push an update with a fix for you soon

**Comment by Falx** [comment]
Should be fixed in 1.4.1

**Comment by nicohagen** [comment]
> Should be fixed in 1.4.1

Thanks, i took the sources from the repo, works perfectly.
