### ISSUE TITLE
Popped up while checking the cooking vendor.

### ISSUE THREAD

**Issue by kgwium** [Falx/StoredAnimaCounter#5]
I am able replicate this error over and over again,  by swapping into "unavailable" part at the cooking vendor, you have to have something in there that you haven´t learned.

----------------------------------------------------------------------------------------------------------------------------

9x Usage: local isAnimaItem = C_Item.IsAnimaItemByID(itemInfo)
[string "=[C]"]: in function `IsAnimaItemByID'
[string "@StoredAnimaCounter\main.lua"]:70: in function <StoredAnimaCounter\main.lua:67>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "Usage: local isAnimaItem = C_Item.IsAnimaItemByID(itemInfo)"

**Comment by Falx** [comment]
Thank you for reporting this. I fixed it in version 1.6.1 which is building now.
